version: '3'

services:
    php56:
      image: php:5.6-alpine
      container_name: php56
#      tty: true
      stdin_open: true
      working_dir: '/app'
      volumes:
        - ./app:/app

    php74:
      image: php:7.4-alpine
      container_name: php74
      working_dir: '/app'
      volumes:
        - ./app:/app
#      tty: true
      stdin_open: true

    php81:
      image: php:8.1-alpine
      container_name: php81
      working_dir: '/app'
      volumes:
        - ./app:/app
#      tty: true
      stdin_open: true
